config/routes.rb
Rails.application.routes.draw do

	root 'task_list#show'

  get 'task/new' => 'task#new'
  post 'task/create' => 'task#create'
  post 'task/status_update' => 'task#status_update'
  post 'task/delete' => 'task#delete'
  get 'task_list/show_subtask/:id(.:format)' => 'task_list#show_subtask' , as: :get_show_subtask
  post 'task_list/show_subtask/:id(.:format)' => 'task_list#show_subtask', as: :post_show_subtask
  get 'subtask/new' => 'subtask#new'
  post 'subtask/create' => 'subtask#create'
  post 'subtask/status_update' => 'subtask#status_update'
  post 'subtask/delete' => 'subtask#delete'

end

app/models/concerns/base_task_form.rb
class BaseTaskForm
  include ActiveModel::Model
  attr_accessor :id, :task_name, :status, :is_deleted, :developer_id

end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
end

app/models/subtask_form.rb
class SubtaskForm < BaseTaskForm
  def initialize(id = nil, task_name = nil, status = nil, is_deleted = nil, developer_id = nil)
    @id = id
    @task_name = task_name
    @status = status
    @is_deleted = is_deleted
    @developer_id = developer_id
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks
end

app/models/task_form.rb
class TaskForm < BaseTaskForm
  attr_accessor :subtask_id_list

  def initialize(id = nil, task_name = nil, status = nil, is_deleted = nil, developer_id = nil, subtask_id_list = [])
    @id = id
    @task_name = task_name
    @status = status
    @is_deleted = is_deleted
    @developer_id = developer_id
    @subtask_id_list = subtask_id_list
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subtask_controller.rb
class SubtaskController < ApplicationController
  before_action :set_users
  def new
    @form = SubtaskForm.new
    @task_id = params[:task_id]
    flash[:task_id] = params[:task_id]
  end

  def create
    subtask = params[:subtask_form]
    task_id = flash[:task_id]
    SubtaskRepository.new.create(subtask[:task_name], subtask[:status], subtask[:is_deleted], subtask[:developer_id], task_id)
    redirect_to get_show_subtask_path(task_id)
  end

  def status_update
    task = Subtask.find(params[:subtask_id])
    SubtaskRepository.new.status_update(task)
    redirect_to get_show_subtask_path(params[:task_id])
  end

  def delete
    task = Subtask.find(params[:subtask_id])
    SubtaskRepository.new.delete(task)
    redirect_to get_show_subtask_path(params[:task_id])
  end

  def set_users
    @users = UserRepository.new.find_all
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :set_users
  def new
    @form = TaskForm.new
  end

  def create
    task = params[:task_form]
    TaskRepository.new.create(task[:task_name], task[:status], task[:is_deleted], task[:developer_id])
    redirect_to root_path
  end

  def status_update
    task = Task.find(params[:id])
    TaskRepository.new.status_update(task)
    redirect_to root_path
  end

  def delete
    task = Task.find(params[:id])
    TaskRepository.new.delete(task)
    redirect_to root_path
  end

  def set_users
    @users = UserRepository.new.find_all
  end
end

app/controllers/task_list_controller.rb
class TaskListController < ApplicationController
	before_action :set_users

	def show
		@tasks = TaskRepository.new.find
	end

	def show_subtask
		task = Task.find(params[:id])
		@task_name = task.task_name
		@task_status = task.status
		@task_id = params[:id]
		@subtasks = SubtaskRepository.new.find_by_task_id(params[:id])
	end

	def set_users
		@users = UserRepository.new.find_all
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_list_helper.rb
module TaskListHelper
  def unchangeable_status?(status, id_list = nil)
    status == 'done' || id_list.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicJira</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Jiraっぽい何か</h1>

<%= yield %>

</body>
</html>

app/views/partials/_new_input.html.haml
= form_for @form, url: {action: 'create'} do |f|
  = f.hidden_field :status, value: 'todo'
  = f.hidden_field :is_deleted, value: false

  = f.label :task_name, 'タスク名'
  = f.text_field :task_name
  %br
  = f.label :developer_id, '担当者'
  = f.select :developer_id, @users.map{|t| [t.user_name, t.developer_id]}
  %br
  = f.submit '作成する'

app/views/subtask/new.html.haml
%h2 新規サブタスク作成

= render partial: 'partials/new_input'

= link_to '戻る', get_show_subtask_path(@task_id)

app/views/task/new.html.haml
%h2 新規タスク作成

= render partial: 'partials/new_input'

= link_to '戻る', root_path

app/views/task_list/show.html.haml
%h2 タスク一覧

= link_to 'タスクを作成する', task_new_path

- if @tasks.present?
  %table
    %tr
      %th タスク名
      %th ステータス
      %th 担当者

    - @tasks.each do |task|
      - user = @users.find_by(developer_id: task.developer_id)
      %tr
        %td
          %sapn= task.task_name
        %td
          - if unchangeable_status?(task.status, task.subtask_id_list)
            %span= task.status
          - else
            = button_to "#{task.status}", task_status_update_path(id: task.id)
        %td
          %span= user.user_name if user.present?
        %td
          = button_to 'サブタスク一覧', get_show_subtask_path(task.id)
        %td
          = button_to '削除する', task_delete_path(id: task.id)

app/views/task_list/show_subtask.html.haml
%h2 #{@task_name}のサブタスク一覧

- unless @task_status == 'done'
  = link_to 'サブタスクを作成する', subtask_new_path(task_id: @task_id)
= link_to '戻る', root_path
- if @subtasks.present?
  %table
    %tr
      %th サブタスク名
      %th ステータス
      %th 担当者

    - @subtasks.each do |task|
      - user = @users.find_by(developer_id: task.developer_id)
      %tr
        %td
          %sapn= task.task_name
        %td
          - if unchangeable_status?(task.status)
            %span= task.status
          - else
            = button_to "#{task.status}", subtask_status_update_path(subtask_id: task.id, task_id: @task_id)
        %td
          %span= user.user_name if user.present?
        %td
          = button_to '削除する', subtask_delete_path(subtask_id: task.id, task_id: @task_id)